# Generated by Django 6.0.2 on 2026-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма платежа"
            ),
        ),
    ]
