# Generated by Django 6.0.2 on 2026-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                default="Создан", max_length=10, verbose_name="Статус платежа"
            ),
        ),
    ]
