# Generated by Django 6.0.1 on 2026-01-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="название курса"),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="описание курса",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="название урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="описание урока",
                    ),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True, null=True, verbose_name="ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.course",
                    ),
                ),
            ],
        ),
    ]
