# Generated by Django 6.0.1 on 2026-01-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "уроки"},
        ),
    ]
