# Generated by Django 6.0.1 on 2026-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rub_price",
            field=models.DecimalField(
                decimal_places=2,
                default=100000,
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
    ]
