# Generated by Django 6.0.2 on 2026-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_rub_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rub_price",
            field=models.PositiveIntegerField(
                blank=True, default=100000, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
